[package]
name = "jadpo-syntax"
description = "Lexer, parser, and syntax tree for the Jadpo language"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
jadpo-diagnostics = { path = "../diagnostics" }

[lib]
path = "src/lib.rs"
