//! Binding-owned typed edges are never ordinary CallEdges or policy effects.
use crate::delivery_phases::{DeliveryTargetCandidate, DeliveryTargetKind};
use crate::{DeliveryHookCandidate, DeliveryPhaseCandidate};
use jadpo_semantic::{NodeKind, SemanticGraph};
use serde_json::{json, Value};
use std::collections::BTreeSet;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DeliveryPrivateNode {
    identity: String,
    kind: NodeKind,
}
impl DeliveryPrivateNode {
    pub fn identity(&self) -> &str {
        &self.identity
    }
    pub fn kind(&self) -> NodeKind {
        self.kind
    }
}
#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub struct DeliveryPrivateEdge {
    phase: &'static str,
    kind: &'static str,
    target: String,
    private_target: bool,
}
impl DeliveryPrivateEdge {
    pub fn phase(&self) -> &str {
        self.phase
    }
    pub fn kind(&self) -> &str {
        self.kind
    }
    pub fn target_identity(&self) -> &str {
        &self.target
    }
}
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DeliveryPrivateGraph {
    binding: String,
    nodes: [DeliveryPrivateNode; 2],
    edges: Vec<DeliveryPrivateEdge>,
}
impl DeliveryPrivateGraph {
    pub fn nodes(&self) -> &[DeliveryPrivateNode] {
        &self.nodes
    }
    pub fn edges(&self) -> &[DeliveryPrivateEdge] {
        &self.edges
    }
    pub fn source_facts(&self) -> Value {
        json!({"schema_version":1, "binding":self.binding,
            "nodes":self.nodes.iter().map(|node| json!({"identity":node.identity, "kind":node.kind.as_str()})).collect::<Vec<_>>(),
            "edges":self.edges.iter().map(|edge| json!({"phase":edge.phase,"kind":edge.kind,"target":edge.target,"private_target":edge.private_target})).collect::<Vec<_>>(),
            "ordinary_call_edges":false, "live_authority_established":false})
    }
    pub(super) fn resolve(
        phases: &DeliveryPhaseCandidate,
        hooks: &DeliveryHookCandidate,
        graph: &SemanticGraph,
    ) -> Option<Self> {
        let binding = phases.binding_candidate().to_owned();
        if phases.job_candidate() != hooks.job_candidate()
            || graph.node(phases.job_candidate())?.kind != NodeKind::Job
        {
            return None;
        }
        let nodes = [
            DeliveryPrivateNode {
                identity: format!("{binding}.selection"),
                kind: NodeKind::DeliverySelection,
            },
            DeliveryPrivateNode {
                identity: format!("{binding}.completion"),
                kind: NodeKind::DeliveryCompletion,
            },
        ];
        if nodes
            .iter()
            .any(|node| graph.node(&node.identity).is_some())
        {
            return None;
        }
        let mut edges = BTreeSet::new();
        for DeliveryTargetCandidate {
            phase,
            kind,
            target,
        } in phases.graph_target_candidates()
        {
            let private_target = matches!(
                kind,
                DeliveryTargetKind::PrivateRead | DeliveryTargetKind::PrivateWrite
            );
            if !matches!(phase, "selection" | "admission" | "dispatch" | "completion") {
                return None;
            }
            if private_target {
                // Exact closed state identities generated by the typed table.
                if ![
                    "claim_fence",
                    "invocation_budget",
                    "receipt",
                    "revision_intent",
                    "todo_schedule_revision",
                ]
                .iter()
                .any(|name| target == format!("{binding}.{name}"))
                {
                    return None;
                }
            } else {
                let actual = graph.node(&target)?.kind;
                let valid = match kind {
                    DeliveryTargetKind::Read => {
                        matches!(actual, NodeKind::Field | NodeKind::Relationship)
                    }
                    DeliveryTargetKind::Write => actual == NodeKind::Field,
                    DeliveryTargetKind::Predicate => actual == NodeKind::LifecycleVisibility,
                    DeliveryTargetKind::Invoke => actual == NodeKind::ServiceOperation,
                    DeliveryTargetKind::Validator => actual == NodeKind::CredentialValidation,
                    DeliveryTargetKind::Membership => actual == NodeKind::Entity,
                    DeliveryTargetKind::Role => actual == NodeKind::EnumVariant,
                    DeliveryTargetKind::ServicePrincipal => actual == NodeKind::PrincipalVariant,
                    DeliveryTargetKind::PrivateRead | DeliveryTargetKind::PrivateWrite => false,
                };
                if !valid {
                    return None;
                }
            }
            edges.insert(DeliveryPrivateEdge {
                phase,
                kind: kind.name(),
                target,
                private_target,
            });
        }
        for (kind, callable) in hooks.graph_callable_candidates() {
            if graph.node(callable)?.kind != NodeKind::Action {
                return None;
            }
            edges.insert(DeliveryPrivateEdge {
                phase: "selection",
                kind,
                target: callable.to_owned(),
                private_target: false,
            });
        }
        Some(Self {
            binding,
            nodes,
            edges: edges.into_iter().collect(),
        })
    }
}
