[package]
name = "jadpo-cli"
description = "Command-line interface for Jadpo"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "jadpo"
path = "src/main.rs"

[dependencies]
ctrlc = "3"
jadpo-core = { path = "../core" }
jadpo-diagnostics = { path = "../diagnostics" }
jadpo-semantic = { path = "../semantic" }
jadpo-syntax = { path = "../syntax" }
serde_json = "1"
