[workspace]
members = [
    "crates/cli",
    "crates/core",
    "crates/diagnostics",
    "crates/semantic",
    "crates/syntax",
]
resolver = "2"

[workspace.package]
edition = "2021"
homepage = "https://jadpo.dev/"
documentation = "https://jadpo.dev/docs/"
license = "UNLICENSED"
rust-version = "1.78"
version = "0.0.1"
